### ISSUE TITLE
Add reference to Clojure in X minutes

### ISSUE THREAD

**Issue by kumarshantanu** [kirang89/clojure-newbie-guide#1]
I usually suggest https://learnxinyminutes.com/docs/clojure/ to Clojure newbies to get a taste of Clojure at the REPL, after setting up Java/Leiningen. Perhaps you would want to mention that resource.

**Comment by kirang89** [comment]
Sure thing. I'll add the change over the weekend. Thanks for the suggestion :)

**Comment by kirang89** [comment]
Done.
