### ISSUE TITLE
remove link for tryclj

### ISSUE THREAD

**Issue by uvtc** [kirang89/clojure-newbie-guide#9]
It's no longer available.

**Comment by kirang89** [comment]
Thanks for pointing it out! Would you like to submit a PR?

**Comment by uvtc** [comment]
No, thank you. Just wanted to point out the issue.

**Comment by kirang89** [comment]
Fixed in [7f8179](https://github.com/kirang89/clojure-newbie-guide/commit/7f8179819d6a40b0c234dbee3de4ef195847482d)
